version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - 3100:3100
    volumes:
      - ./api:/app/apiaxle/api
      - ./base:/app/apiaxle/base
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEBUG_MODE: 'false'
    command: ['api', '3100']

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - 3000:3000
    volumes:
      - ./proxy:/app/apiaxle/proxy
      - ./base:/app/apiaxle/base
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEBUG_MODE: 'false'
    command: ['proxy', '3000']

  repl:
    build:
      context: .
      dockerfile: Dockerfile-development
    volumes:
      - ./repl:/app/apiaxle/repl
      - ./api:/app/apiaxle/api
      - ./proxy:/app/apiaxle/proxy
      - ./base:/app/apiaxle/base
      - ./.git:/app/apiaxle/.git
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEBUG_MODE: 'true'
    command: ['repl']

  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379"
