fs     = require "fs"
util   = require "util"

{ jsBuild,
  jsClean,
  fixHashbang,
  test } = require "../base/lib/cakefile_tasks"

option "-w", "--watch", "rebuild them when they change"
task "js:build", "Build the front-end javascript", ( options ) ->
  jsBuild options, [ "lib/**/*.coffee",
                     "test/**/*.coffee",
                     "apiaxle.coffee" ]

task "js:clean", "Build the front-end javascript", ( options ) ->
  jsClean options, [ "lib/**/*.js",
                     "test/**/*.js",
                     "apiaxle.js" ]

task "test", "Run the tests.", test

task "fixHashbang", "Fix the hashbangs in the exes", ( options ) ->
  fixHashbang options, "apiaxle.js"
