fs     = require "fs"
util   = require "util"

{ jsBuild,
  jsClean,
  fixHashbang,
  lint
  test } = require "../base/lib/cakefile_tasks"

coffee_globs = [ "lib/**/*.coffee",
                 "test/**/*.coffee",
                 "apiaxle.coffee" ]

option "-w", "--watch", "rebuild them when they change"
task "js:build", "Build the front-end javascript", ( options ) ->
  jsBuild options, coffee_globs

task "js:clean", "Build the front-end javascript", ( options ) ->
  jsClean options, [ "lib/**/*.js",
                     "test/**/*.js",
                     "apiaxle.js" ]

task "lint", "Lint the coffeescript", ( o ) -> lint o, coffee_globs
task "test", "Run the tests.", test

task "fixHashbang", "Fix the hashbangs in the exes", ( options ) ->
  fixHashbang options, "apiaxle.js"
