async  = require "async"
fs     = require "fs"
util   = require "util"

{ Apiaxle } = require "./apiaxle_proxy"
{ spawn }  = require "child_process"

task "test", "Run the tests.", ( options ) ->
  script = spawn "./bin/run-tests.bash"

  script.stdout.on "data", util.print
  script.stderr.on "data", util.print
  script.on "exit", ( code, signal ) -> process.exit code
