fs     = require "fs"
util   = require "util"

{ jsBuild,
  jsClean,
  fixHashbang,
  test } = require "../base/lib/cakefile_tasks"

option "-w", "--watch", "rebuild them when they change"
task "js:build", "Build the front-end javascript", ( options ) ->
  jsBuild options, [ "app/**/*.coffee",
                     "lib/**/*.coffee",
                     "bin/**/*.coffee",
                     "apiaxle-proxy.coffee" ]

task "js:clean", "Build the front-end javascript", ( options ) ->
  jsClean options, [ "app/**/*.js",
                     "lib/**/*.js",
                     "bin/**/*.coffee",
                     "apiaxle-proxy.js" ]

task "fixHashbang", "Fix the hashbangs in the exes", ( options ) ->
  fixHashbang options, "apiaxle-proxy.js"

task "test", "Run the tests.", test
