{ test, jsBuild, jsClean } = require "./lib/cakefile_tasks"
{ spawn }  = require "child_process"

option "-w", "--watch", "rebuild them when they change"
task "js:build", "Build the front-end javascript", ( options ) ->
  jsBuild options, [ "app/**/*.coffee", "lib/**/*.coffee", "apiaxle-api.coffee" ]

task "js:clean", "Build the front-end javascript", ( options ) ->
  jsClean options, [ "app/**/*.js", "lib/**/*.js", "apiaxle-api.js" ]

task "test", "Run the tests.", test
